language: python

# The default python version on Travis is 2.7
# But we add this line to show the python version in the Travis UI
python: "2.7"

os:
  - linux
  ## We also run two macOS jobs with python 2 and 3

## Default env vars
env:
  global:
    ## Most builds use the standard command names
    - PYTHON="python"
    - PIP="pip"
  matrix:
    ## This matrix entry is required, but it doesn't actually create any jobs
    -

## We don't use the build matrix cross-product, because it makes too many jobs
## Instead, we list each job under matrix: include:
matrix:
  # include creates Linux, python 2.7 builds by default
  # the key(s) in each item override these defaults
  include:
    ## macOS on Travis is tricky:
    ##   - We use the default python version on macOS, which is currently 2.7.
    ##     (But we don't show the version, because Travis might change it
    ##     without us noticing.)
    ##   - We use language: c, because language: python fails on Travis macOS.
    - os: osx
      language: c
      python:
      addons:
        ## (macOS only)
        homebrew:
          packages:
            ## macOS needs pip(2) from homebrew python
            - python@2
          ## See ticket #30928 for more information. This key should be
          ## removed at some point to speed up builds.
          update: true
    - os: osx
      language: c
      python:
      ## python 3 is already installed, under these names
      env: PYTHON="python3" PIP="pip3"

    ## Test all supported python releases
    ## Pre-installed in Travis Bionic:
    ## https://docs.travis-ci.com/user/reference/bionic/#python-support
    ## End of Life: 1 January 2020
    ## https://www.python.org/dev/peps/pep-0373/#update
    - python: "2.7"

    ### TODO: the fallback scripts don't work with python 3 yet ###
    ### See chutney's .travis.yml for the latest python version list ###

    ## PyPy versions
    ## End of Life: "forever"
    ## http://doc.pypy.org/en/latest/faq.html#how-long-will-pypy-support-python2
    ## But stem or fallback-scripts may decide not to support python 2
    ## after 1 Jan 2020.
    - python: "pypy"
      dist: xenial

    ### TODO: the fallback scripts don't work with python 3 yet ###
    ### See chutney's .travis.yml for the latest python version list ###
    - python: "3.6"
    - python: "nightly"
    - python: "pypy3"
      dist: xenial

  ## Uncomment to allow the build to report success (with non-required
  ## sub-builds continuing to run) if all required sub-builds have
  ## succeeded.  This is somewhat buggy currently: it can cause
  ## duplicate notifications and prematurely report success if a
  ## single sub-build has succeeded.  See
  ## https://github.com/travis-ci/travis-ci/issues/1696
  #fast_finish: true

  ## These builds fail in Travis at the moment
  allow_failures:
    - python: "3.6"
    - python: "nightly"
    - python: "pypy3"
    ## (macOS only)
    - env: PYTHON="python3" PIP="pip3"

## (Linux only) Use a recent Linux image (Ubuntu Bionic)
dist: bionic

## (macOS only) Use a recent macOS image
## See https://docs.travis-ci.com/user/reference/osx#os-x-version
## Default is Xcode 9.4 on macOS 10.13 as of October 2019
## Recent is Xcode 11.2 on macOS 10.14 as of October 2019
osx_image: xcode11.2

before_install:
  ## Set pipefail: we use pipes
  - set -o pipefail || echo "pipefail failed"

install:
  ## List installed package versions
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then dpkg-query --show; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list --versions; fi
  - $PYTHON --version
  ## Are we running python 2?
  - if $PYTHON --version 2>&1 | cut -d" " -f2 | grep -q '2[.]'; then PY2=1; else PY2= ; fi
  ## We could install stem's dependencies, but they are all optional
  - $PIP install -U pip
  - $PIP install -r requirements.txt
  - if [[ "$PY2" ]]; then $PIP install -r requirements-python2.txt; fi
  ## Now list installed python package versions
  - $PIP list

script:
  ## Run some fallback-scripts tests
  ## Outputs fallback.log with info-level logs
  - ./test.sh

after_failure:
  ## Show all the output, including info-level logs
  - cat fallback.log || echo "cat failed"

notifications:
  irc:
    channels:
      - "irc.oftc.net#tor-ci"
    template:
      - "%{repository} %{branch} %{commit} - %{author}: %{commit_subject}"
      - "Build #%{build_number} %{result}. Details: %{build_url}"
    on_success: change
    on_failure: change
  email:
    on_success: never
    on_failure: change
